---
image:
  os: Windows 10
  edition: Professional
  language: en-US
  architecture: x86-64
  timezone: UTC
  hostname: '*'
  gpu: false
  owner: Mozilla RelOps
  organization: Mozilla Corporation
  partition: MBR
  format: VHD
  type: Fixed
  target:
    platform: amazon
    bucket: windows-ami-builder
iso:
  source:
    platform: amazon
    bucket: windows-ami-builder
    key: iso/en_windows_10_business_editions_version_1903_updated_sept_2019_x64_dvd_a10b235d.iso
  wimindex: 5
manager:
  pool:
  - domain: gecko-t
    variant: win10-64-azure
    capacity:
      minimum: 0
      maximum: 3
    locations:
    - centralus
    lifecycle: normal
    owner: grenade@mozilla.com
    provider: azure
    platform: azure
target:
- platform: azure
  group: rg-central-us-gecko-t
  region: Central US
  hostname: &hostname
    format: vm-{0}
    slug:
      type: uuid
      length: 12
  machine: &machine
    cpu: 3
    ram: 14
    format: Standard_DS{0}_v2
  disk: &disk
  - os: true
    source: windows10-professional-en-us-x86-64
    variant: ssd
    size: 64
  - os: false
    variant: ssd
    size: 128
  - os: false
    variant: ssd
    size: 128
  network:
    name: vn-central-us-gecko-t
    prefix: '10.0.0.0/24'
    dns: &dns
    - '1.1.1.1'
    - '1.0.0.1'
    subnet:
      name: sn-central-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-central-us-gecko-t
      rules: &rules
      - name: allow-rdp
        description: 'allow: inbound tcp connections, for: rdp, from: whitelist, to: any host, on port: 3389'
        access: Allow
        protocol: Tcp
        direction: Inbound
        priority: 110
        sourceAddressPrefix:
        - 185.189.196.104
        - 185.189.196.216
        - 185.189.199.208
        sourcePortRange: '*'
        destinationAddressPrefix: '*'
        destinationPortRange: 3389
      - name: allow-ssh
        description: 'allow: inbound tcp connections, for: ssh, from: whitelist, to: any host, on port: 22'
        access: Allow
        protocol: Tcp
        direction: Inbound
        priority: 111
        sourceAddressPrefix:
        - 185.189.196.104
        - 185.189.196.216
        - 185.189.199.208
        sourcePortRange: '*'
        destinationAddressPrefix: '*'
        destinationPortRange: 22
  tag: &tag
  - name: workerType
    value: gecko-t-win10-64-azure
  - name: sourceOrganisation
    value: mozilla-platform-ops
  - name: sourceRepository
    value: ronin_puppet
  - name: sourceRevision
    value: cloud_windows
  - name: sourceScript
    value: provisioners/windows/azure/azure-bootstrap.ps1
  - name: deploymentId
    value: 9bad2b7
- platform: azure
  group: rg-east-us-gecko-t
  region: East US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-gecko-t
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-gecko-t
      rules: *rules
  tag: *tag
- platform: azure
  group: rg-east-us-2-gecko-t
  region: East US 2
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-east-us-2-gecko-t
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-east-us-2-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-east-us-2-gecko-t
      rules: *rules
  tag: *tag
- platform: azure
  group: rg-north-central-us-gecko-t
  region: North Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-north-central-us-gecko-t
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-north-central-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-north-central-us-gecko-t
      rules: *rules
  tag: *tag
- platform: azure
  group: rg-south-central-us-gecko-t
  region: South Central US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-south-central-us-gecko-t
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-south-central-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-south-central-us-gecko-t
      rules: *rules
  tag: *tag
- platform: azure
  group: rg-west-us-gecko-t
  region: West US
  hostname: *hostname
  machine: *machine
  disk: *disk
  network:
    name: vn-west-us-gecko-t
    prefix: '10.0.0.0/24'
    dns: *dns
    subnet:
      name: sn-west-us-gecko-t
      prefix: '10.0.0.0/24'
    flow:
      name: nsg-west-us-gecko-t
      rules: *rules
  tag: *tag
